
Neos:
  RedirectHandler:
    features:
      hitCounter: true
    statusCode:
      redirect: 307
      gone: 410
    cancelHttpChain: true
  Flow:
    http:
      chain:
        process:
          chain:
            redirect:
              position: 'after routing'
              component: Neos\RedirectHandler\RedirectComponent
